import type { Metadata } from 'next'
import Link from 'next/link'
import 'styles/globals.css'
import styles from './layout.module.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ja">
      <body className={styles.body}>
        <header className={styles.header}>
          <h1>
            <Link href="/">トップページ</Link>
          </h1>
        </header>
        <main className={styles.main}>{children}</main>
      </body>
    </html>
  )
}
